### ISSUE TITLE
Add support for OpenAPI 3.10 definitions

### ISSUE THREAD

**Issue by jclsn** [haishanh/coc-swagger#60]
I can't render my OpenAPI 3.1.0 definitions. Can you update this?

**Comment by haishanh** [comment]
Could you try the latest `coc-swagger@0.0.4` and let me know the result?

Thanks.

**Comment by jclsn** [comment]
Just tested it. Works! :)

**Comment by jclsn** [comment]
Is there a way to also get a linter btw? I've looked at some Github repos but they all don't seem maintained anymore
